[package]
name = "funcount2sym"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
addr2line = "0.20"
goblin = "0.9.2"
memmap2 = "0.9.5"
procfs = "0.17.0"
