#!/usr/bin/python3
import sys
import os
import subprocess
linking = '-c' not in sys.argv and '-S' not in sys.argv and '-E' not in sys.argv
args = sys.argv[1:]
if linking:
    srcdir = os.path.dirname(os.path.dirname(__file__))
    args += [os.path.join(srcdir, f) for f in ['funtrace.cpp', 'funtrace_pg.S']] + '-g -pthread -ldl'.split()
else:
    args += '-g -pthread -pg -mfentry -minstrument-return=call'.split()
gxxpath = subprocess.getoutput('which g++')
os.execl(gxxpath, *([gxxpath] + args))
